// Data-driven registry: loads crates/rct-core/data/registry.csv (generated by
// tools/generate_registry.py from the vendored python-rctclient).
//
// Keeping the registry as DATA is the update mechanism: re-run the generator,
// the golden test compares count + samples against the Python source.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::types::{DataType, ObjectGroup};

#[derive(Debug)]
pub struct ObjectInfo {
    pub group: ObjectGroup,
    pub object_id: u32,
    pub index: i32,
    pub name: &'static str,
    pub request_data_type: DataType,
    pub response_data_type: DataType,
    pub unit: &'static str,
    pub description: &'static str,
    /// "0=Foo|1=Bar" style enum mapping, pre-parsed lazily by callers.
    pub enum_map_raw: &'static str,
}

impl ObjectInfo {
    pub fn enum_str(&self, value: u32) -> Option<&'static str> {
        if self.request_data_type != DataType::Enum || self.enum_map_raw.is_empty() {
            return None;
        }
        self.enum_map_raw
            .split('|')
            .find(|p| p.starts_with(&format!("{value}=")))
            .map(|p| &p[p.find('=').unwrap() + 1..])
    }
}

pub struct Registry {
    by_name: HashMap<&'static str, &'static ObjectInfo>,
    by_id: HashMap<u32, &'static ObjectInfo>,
    all: &'static [ObjectInfo],
    pub source_commit: &'static str,
    pub count: usize,
}

const CSV: &str = include_str!("../data/registry.csv");
const META: &str = include_str!("../data/registry_meta.json");

fn leak_str(s: &str) -> &'static str {
    Box::leak(s.to_string().into_boxed_str())
}

fn build() -> &'static Registry {
    static REG: OnceLock<&'static Registry> = OnceLock::new();
    REG.get_or_init(|| {
        let mut lines = CSV.lines();
        let header = lines.next().unwrap();
        let cols: Vec<&str> = header.split(';').collect();
        let idx = |c: &str| cols.iter().position(|x| *x == c).unwrap();

        let mut entries: Vec<ObjectInfo> = Vec::new();
        for line in lines {
            if line.is_empty() {
                continue;
            }
            // simple CSV split: our generator never quotes (values have no ';')
            let f: Vec<&str> = line.split(';').map(|s| s.trim_end_matches('\r')).collect();
            let get = |c: &str| f.get(idx(c)).copied().unwrap_or("");
            entries.push(ObjectInfo {
                group: ObjectGroup::from_string(get("group")).unwrap_or(ObjectGroup::Others),
                object_id: u32::from_str_radix(get("object_id").trim_start_matches("0x"), 16).unwrap(),
                index: get("index").parse().unwrap_or(-1),
                name: leak_str(get("name")),
                request_data_type: DataType::from_str_name(get("req_type")).unwrap_or(DataType::Unknown),
                response_data_type: DataType::from_str_name(get("resp_type")).unwrap_or(DataType::Unknown),
                unit: leak_str(get("unit")),
                description: leak_str(get("description")),
                enum_map_raw: leak_str(get("enum_map")),
            });
        }

        // meta: "count": N, "source_commit": "..." (tiny hand-rolled JSON read)
        let count = META
            .lines()
            .find_map(|l| l.split(':').nth(1).and_then(|v| v.trim().trim_end_matches(',').parse::<usize>().ok()))
            .unwrap_or(0);
        let commit = META
            .lines()
            .find(|l| l.contains("source_commit"))
            .and_then(|l| l.split('"').nth(3))
            .unwrap_or("unknown");

        let leaked: &'static [ObjectInfo] = Box::leak(entries.into_boxed_slice());
        let mut by_name = HashMap::new();
        let mut by_id = HashMap::new();
        for o in leaked.iter() {
            by_name.insert(o.name, o);
            by_id.insert(o.object_id, o);
        }
        Box::leak(Box::new(Registry { by_name, by_id, all: leaked, source_commit: commit, count }))
    })
}

pub fn registry() -> &'static Registry {
    build()
}

impl Registry {
    pub fn get_by_name(&self, name: &str) -> Option<&'static ObjectInfo> {
        self.by_name.get(name).copied()
    }
    pub fn get_by_id(&self, id: u32) -> Option<&'static ObjectInfo> {
        self.by_id.get(&id).copied()
    }
    pub fn all(&self) -> &[ObjectInfo] {
        self.all
    }
    pub fn group(&self, g: ObjectGroup) -> impl Iterator<Item = &ObjectInfo> {
        self.all.iter().filter(move |o| o.group == g)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_samples() {
        let r = registry();
        let soc = r.get_by_name("battery.soc").unwrap();
        assert_eq!(soc.object_id, 0x959930bf);
        assert_eq!(soc.request_data_type, DataType::Float);
        let strat = r.get_by_name("power_mng.soc_strategy").unwrap();
        assert_eq!(strat.object_id, 0xF168B748);
        assert_eq!(strat.request_data_type, DataType::Enum);
        let p = r.get_by_name("p_rec_lim[1]").unwrap();
        assert_eq!(p.object_id, 0x54829753);
        assert_eq!(p.unit, "W");
        // reverse lookup
        assert_eq!(r.get_by_id(0x959930bf).unwrap().name, "battery.soc");
    }

    #[test]
    fn count_matches_meta() {
        let r = registry();
        assert_eq!(r.all().len(), r.count);
        assert!(r.count >= 900, "registry suspiciously small: {}", r.count);
    }

    #[test]
    fn soc_strategy_enum_map() {
        let r = registry();
        let strat = r.get_by_name("power_mng.soc_strategy").unwrap();
        assert_eq!(strat.enum_str(4), Some("Internal"));
        assert_eq!(strat.enum_str(2), Some("External"));
    }
}
